source('scripts/run_coloc.R')
plan <- list(gwas=list(n=1000,cases=300),methods=list(priors=list(p1=1e-4,p2=1e-4)))
snp <- paste0('s',seq_len(200))
z <- c(10,rep(0,199))
gwas <- data.frame(snp=snp,position=seq_len(200),pvalue=2*pnorm(-abs(z)),MAF=0.2,N=1000)
qtl <- data.frame(snp=snp,position=seq_len(200),beta=z*0.1,varbeta=0.01,pvalue=2*pnorm(-abs(z)),MAF=0.2,N=1000)
shared <- baseline_pair(gwas,qtl,plan,1e-6)
stopifnot(shared$summary$PP.H4.abf>0.9,shared$summary$coverage_gate)
reordered <- baseline_pair(gwas,qtl[200:1,],plan,1e-6)
stopifnot(isTRUE(all.equal(shared$summary,reordered$summary,tolerance=1e-12)))
distinct <- qtl
distinct$beta <- c(0,1,rep(0,198))
distinct$pvalue <- 2*pnorm(-abs(distinct$beta/0.1))
separate <- baseline_pair(gwas,distinct,plan,1e-6)
stopifnot(separate$summary$PP.H3.abf>0.9)
missing <- baseline_pair(gwas,qtl[-1,],plan,1e-6)
stopifnot(!missing$summary$coverage_gate,missing$summary$gwas_bf_mass_retained<0.1)
cat('Baseline: shared versus distinct signals, SNP order and missing evidence mass passed\n')
data(coloc_test_data,package='coloc')
a <- coloc::runsusie(coloc_test_data$D3)
b <- coloc::runsusie(coloc_test_data$D4)
res <- coloc::coloc.susie(a,b,p12=1e-6)
stopifnot(any(res$summary$PP.H3.abf>0.9),any(res$summary$PP.H4.abf>0.9))
cat('Official multiple-signal fixture: both shared and distinct signals recovered\n')
